version: '3.7'

services:
  inventory-api-service:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT=${JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT}
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - mariadb-service
  
  mariadb-service:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network

networks:
  my-network: